#!/bin/bash
echo "To manually trigger Vercel deployment:"
echo ""
echo "Option 1: Use Vercel Dashboard"
echo "1. Go to: https://vercel.com/delimatsuo/dressup"
echo "2. Click 'Deployments' tab"
echo "3. Click '...' menu → 'Redeploy'"
echo "4. Or find 'Create Deployment' button"
echo ""
echo "Option 2: Disconnect and Reconnect GitHub"
echo "1. Go to Settings → Git"
echo "2. Click 'Disconnect from GitHub'"
echo "3. Reconnect and select 'delimatsuo/dressup'"
echo "4. This forces webhook refresh"
echo ""
echo "Option 3: Delete Project and Re-import"
echo "1. Settings → Advanced → Delete Project"
echo "2. Go to vercel.com/new"
echo "3. Import delimatsuo/dressup fresh"
echo ""
echo "Current main branch has commit e9e2be6 with ALL fixes"
